### ISSUE TITLE
Trigger on any change except blank

### ISSUE THREAD

**Issue by Z41DL** [squeek502/obs-txt-trigger#5]
If possible, I would really appreciate the functionality of "Trigger on any change in file contents", except not when the text file is empty.

I am using it for speech-to-text captioning, and the idea is that the text file is constantly edited when users speak. 
It's showing a sound file source as long as it is being edited. 
Whenever no words have been captured for 10 seconds, the file is edited to be blank, which is counting as a trigger.

**Comment by squeek502** [comment]
Sure thing, added in v0.3.1. Let me know if it does what you expect: https://github.com/squeek502/obs-txt-trigger/releases/tag/v0.3.1
