### ISSUE TITLE
Enable source indefinitely, until changes stop

### ISSUE THREAD

**Issue by Z41DL** [squeek502/obs-txt-trigger#6]
The last version was exactly what I hoped for, thank you so much I really appreciate it!
However, I'm sorry to be a bother again, I think this change would make the OBS script perfect for my setup.

Regarding "Trigger on any change in file contents",
when the first edit is detected, an option which shows the source indefinitely except when no changes have been detected for (x) seconds.

Attached is a video of the usage:
https://user-images.githubusercontent.com/116803805/198580105-4c1d74aa-c13a-455b-a2b0-5593740a2f5c.mp4

The audio sounds strange due to the source auto-hiding briefly in between caption updates.

**Comment by squeek502** [comment]
Makes sense, will get to this soon.

**Comment by squeek502** [comment]
Added in v0.3.2: https://github.com/squeek502/obs-txt-trigger/releases/tag/v0.3.2

Very cool use-case btw, it's always interesting to see how the script gets used.
